import { test, } from '@playwright/test';

test('test', async ({ page }) => {
  await page.getByRole('link', { name: 'Sign in' }).click();
  await page.getByTestId('input-email').click();
  await page.getByTestId('input-email').fill('admin');
  await page.getByTestId('input-email').press('Enter');
  await page.getByTestId('input-password').press('CapsLock');
  await page.getByTestId('input-password').fill('T');
  await page.getByTestId('input-password').press('CapsLock');
  await page.getByTestId('input-password').fill('Test?123');
  await page.getByTestId('input-password').press('Enter');
  await page.getByRole('button', { name: 'TR' }).click();
  await page.getByRole('heading', { name: 'Sanat Durağı' }).click();
  await page.getByText('"Farklı renklerin buluşma').click();
  await page.getByRole('link', { name: 'Eserlere Gözat' }).click();
  await page.getByText('Kategoriler').click();
  await page.getByText('resim', { exact: true }).click();
  await page.locator('.css-1tet98h > div:nth-child(3)').first().click();
  await page.getByRole('img', { name: 'İhmal edilen hayatlar' }).click();
  await page.getByText('dijital resim').click();
  await page.getByText('Tanıtım').click();
  await page.getByText('Diger').click();
  await page.getByText('Dijital Art').click();
  await page.locator('p').filter({ hasText: 'Koleksiyonlar' }).click();
  await page.getByRole('button', { name: 'NL' }).click();
  await page.getByRole('link', { name: 'Kunsten' }).first().click();
  await page.getByRole('link', { name: 'Collecties' }).first().click();
  await page.getByRole('link', { name: 'Activiteiten' }).click();
  await page.getByRole('link', { name: 'Over Ons' }).first().click();
  await page.getByRole('link', { name: 'Contact' }).first().click();
  await page.getByRole('link', { name: 'Donatie' }).first().click();
});