import { AuthContextType } from './types'

export const initialAuthState: AuthContextType = {
  isLoading: false,
  error: null,
  token: null,
  user: null,
  profile: null,
  roles: ['public'],
  permissions: {},
  demoPermissions: null,
  setDemoPermissions: () => {},
  setPermissions: () => {},
  openAuthModal: () => {},
  closeAuthModal: () => {},
  isAuthModalOpen: false,
  checkAuth: () => Promise.resolve(initialAuthState),
  login: () => Promise.resolve(initialAuthState),
  logout: () => Promise.resolve(),
  register: () => Promise.resolve(initialAuthState),
  canCreate: () => false,
  canRead: () => false,
  canUpdate: () => false,
  canDelete: () => false,
  checkActionsPermission: () => false,
  isAdmin: () => false,
}
