export const dashboardRoutes = [
  '/',
  '/accounts',
  '/activities',
  '/archive-contents',
  '/arts',
  '/assets',
  '/blogs',
  '/categories',
  '/collections',
  '/courses',
  '/donation',
  '/donations',
  '/foundations',
  '/hashtags',
  '/news',
  '/news/bookmarks',
  '/news/recommended',
  '/notifications',
  '/posts',
  '/profiles',
  '/roles',
  '/tags',
  '/timelines',
  '/timelines/bookmarks',
  '/timelines/recommended',
  '/translates',
  '/user-feedbacks',
  '/users',
  'all',
] as const

type Route = (typeof dashboardRoutes)[number]
export type DashboardRoute = Route | `${Route}?${string}`
