jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run admin tests
        run: yarn nx e2e admin-e2e --browser=chromium
      - name: Run foundation tests
        run: yarn nx e2e foundation-e2e --browser=chromium
      - name: Run kunsthalte tests
        run: yarn nx e2e kunsthalte-e2e --browser=chromium
      - name: Run samenvvv tests
        run: yarn nx e2e samenvvv-e2e --browser=chromium
